name: Examples Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ExamplesTest:
    name: Run `ExamplesTest.sh`
    strategy:
      matrix:
        os:
          - macOS-latest
          # - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      # - run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" || true && brew install swift-sh
      - run: brew install swift-sh
      - run: sh ./Scripts/ExamplesTest.sh
